name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  equatable: ^2.0.3
  weather_icons: ^3.0.0
  iconly: ^1.0.1
  shimmer: ^2.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  faker: ^2.0.0
  bloc_test: ^9.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/icons/rain.png
    - assets/icons/sun.png
    - assets/icons/wind.png

  fonts:
    - family: PT Sans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
